-- FUNÇÕES (MY SQL)
-- https://www.w3schools.com/sql/sql_ref_mysql.asp


-- FUNÇÕES EM STRING
SELECT LTRIM('      OLÁ'); -- RETORNA OLÁ SEM OS ESPAÇOS NA FRENTE
SELECT RTRIM('OLÁ      '); -- RETORNA OLÁ SEM OS ESPAÇOS NO FINAL
SELECT TRIM('      OLÁ      '); -- RETORNA OLÁ SEM OS ESPAÇOS
SELECT CONCAT('OLÁ',' ','TUDO BEM','?') AS RESULTADO; -- CONCATENANDO STRINGS
SELECT UPPER('olá, tudo bem?'); -- COLOCA TUDO EM UPPERCASE
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) as RESULTADO;

SELECT CONCAT(NOME, ' (', CPF,')') AS RESULTADO FROM TABELA_DE_CLIENTES;

-- Faça uma consulta listando o nome do cliente e o endereço completo (Com rua, bairro, cidade e estado).
SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS COMPLETO
FROM tabela_de_clientes;


-- FUNÇÕES COM DATE

SELECT CURRENT_TIMESTAMP(); -- DATA E HORA ATUAL DO COMPUTADOR
SELECT CURRENT_TIME(); -- HORA ATUAL DO COMPUTADOR
SELECT CURRENT_DATE(); -- DATA ATUAL DO COMPUTADOR
SELECT DATEDIFF('2017-06-25', '2016-06-25'); -- TRAS A DIFERENÇA ENTRE UMA DATA E OUTRA (EM DIAS)
SELECT DAYNAME(CURRENT_DATE()); -- EXTRAI O NOME DO DIA DA DATA

SELECT DATEDIFF(CURRENT_TIMESTAMP(),'2019-01-01') AS RESULTADO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(),'1989-05-23') AS RESULTADO; -- PEGA A DATA E VERIFICA QUANTOS DIAS SE PASSARAM ATÉ O MOMENTO

SELECT DISTINCT DATA_VENDA AS 'DATA DA VENDA',
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES, YEAR(DATA_VENDA)
FROM NOTAS_FISCAIS;

-- Crie uma consulta que mostre o nome e a idade atual dos clientes.
SELECT NOME, TIMESTAMPDIFF(YEAR,DATA_DE_NASCIMENTO, CURDATE() )  AS 'IDADE ATUAL'
FROM TABELA_DE_CLIENTES;


-- FUNÇÕES MATEMÁTICAS

SELECT (23+((25-2)/2)*45); -- EXEMPLO DE CALCULO
SELECT CEILING(12.2333232323) AS RESULTADO; -- ARREDONDAMENTO PARA CIMA (RETORNA O MAIOR INTEIRO INDEPENDENTE DAS CASAS DECIMAIS)
SELECT FLOOR(12.2333232323) AS RESULTADO; -- DESCONSIDERA AS CASAS DECIMAIS 
SELECT ROUND(12.333232323) AS RESULTADO; -- ARREDONDAMENTO  (ARREDONDA PARA CIMA SE AS CASAS DECIMAIS FOREM ACIMA DE 5 OU PARA BAIXO SE FOR ABAIXO DE 5)
SELECT RAND() AS RESULTADO; -- NUMERO ALEATÓRIO

SELECT NUMERO, QUANTIDADE, PRECO 
FROM itens_notas_fiscais;
SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE*PRECO, 2) AS 'FATURAMENTO R$'-- USO DO ROUND COM 2 CASAS DECIMAIS
FROM itens_notas_fiscais;

-- Na tabela de notas fiscais temos o valor do imposto. 
-- Já na tabela de itens temos a quantidade e o faturamento. 
-- Calcule o valor do imposto pago no ano de 2016 arredondando para o menor inteiro.

SELECT YEAR(DATA_VENDA) AS ANO , FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) AS IMPOSTO
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);

-- CONVERSÃO DE DADOS
-- BASE DE ABREVIAÇÕES PARA DATA
-- https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_date-format

SELECT CURRENT_TIMESTAMP() AS RESULTADO;
SELECT CONCAT('O DIA DE HOJE É: ', CURRENT_TIMESTAMP()) AS RESULTADO; -- NO FORMATO PADRÃO DO SQL
SELECT CONCAT('O DIA DE HOJE É: ',DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%Y - %U')) AS RESULTADO; -- FORMATO PERSONALIZADO 

SELECT CONVERT(23.3, CHAR) AS RESULTADO_STRING;
SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO; -- CONVERT APENAS O PRIMEIRO NUMERO

-- Queremos construir um SQL cujo resultado seja, para cada cliente:
-- “O cliente João da Silva faturou 120000 no ano de 2016”.
-- Somente para o ano de 2016.

SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CAST(SUM(INF.QUANTIDADE * INF.preco) AS char (20)), ' no ano ', CAST(YEAR(NF.DATA_VENDA) AS char (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA);



